# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'HotProspects_16' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HotProspects_16
  pod 'EFQRCode', '~> 5.1.6'
  
  pod 'FSCalendar', '~> 2.8.1'

end
